### ISSUE TITLE
Chucker broken on OkHttp 4.0

### ISSUE THREAD

**Issue by timnew** [ChuckerTeam/chucker#60]
**Describe the bug**
Chunker doesn't work with okhttp 4.0 due to API incompatibility 

**Error Log:**
```
Caused by: java.lang.NoSuchMethodError: No static method hasBody(Lokhttp3/Response;)Z in class Lokhttp3/internal/http/HttpHeaders; or its super classes (declaration of 'okhttp3.internal.http.HttpHeaders' appears in /data/app/com.jora.android.debug-pyXggfGJ5Y4D-gUqowxVwQ==/split_lib_dependencies_apk.apk!classes2.dex)
    at com.readystatesoftware.chuck.api.ChuckInterceptor.intercept(ChuckInterceptor.java:149)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
    at com.jora.android.ng.network.authentication.AuthInterceptor.intercept(AuthInterceptor.kt:20)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
    at okhttp3.RealCall.execute(RealCall.kt:66)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
    at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
    at io.reactivex.Observable.subscribe(Observable.java:12267)
    at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
    at io.reactivex.Observable.subscribe(Observable.java:12267)
    at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
    at io.reactivex.Single.subscribe(Single.java:3603)
    at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
```

**Comment by cortinico** [comment]
Hey @timnew 
Thanks for the bug report.

Can I ask you to try version `3.0.0-alpha1`?
Version 3 of Chucker is already adapted to work with OkHttp4 (see #52)

**Comment by tusharj9** [comment]
> Hey @timnew
> Thanks for the bug report.
> 
> Can I ask you to try version `3.0.0-alpha1`?
> Version 3 of Chucker is already adapted to work with OkHttp4 (see #52)

Did not worked for me . Still got same exception for alpha1 .

**Comment by timnew** [comment]
Just verified, doesn't work for me either.
I'm checking what caused the issue

**Comment by timnew** [comment]
By checking the code, I feel the code on master branch has fixed the issue but not the `3.0.0-alpha1`

I can see `  if (HttpHeaders.hasBody(response) && responseEncodingIsSupported) {` in `3.0.0-alpha1`, and on master, `hasBody` has been replaced with extension method `com.chuckerteam.chucker.api.internal.support.hasBody`

**Comment by tusharj9** [comment]
Btw  using  develop-SNAPSHOT version worked for me.

**Comment by timnew** [comment]
![image](https://user-images.githubusercontent.com/1287238/60577729-40089a80-9dc3-11e9-9b5f-dfa02f0dd32a.png)

Yes the fix is after the tag. @cortinico would you mind to create a new alpha tag on commit https://github.com/ChuckerTeam/chucker/commit/e7e5a204e42c7fbe27a69cf764cbf4af0b915665

**Comment by gvv-ua** [comment]
On 3.0.0-alpha1 I get the same error

**Comment by timnew** [comment]
As a temp solution, this works and locked version to commit merged PR #54 
```
debugImplementation 'com.github.ChuckerTeam.Chucker:library:e7e5a204e4'
releaseImplementation 'com.github.ChuckerTeam.Chucker:library-no-op:e7e5a204e4'
```

**Comment by timnew** [comment]
I'm happy to close this issue, as the bug has been fixed on master. Or you wish to wait until the version is released? @cortinico

**Comment by cortinico** [comment]
> By checking the code, I feel the code on master branch has fixed the issue but not the 3.0.0-alpha1

Hey @timnew 
Yes you're correct. The fix was on `develop` but I haven't released any other version after that.
I'm about to release `3.0.0-alpha2` today so you can pin to that version :)

Let's close the issue and we're going to have the `3.0.0` stable really soon
