### ISSUE TITLE
Android resource linking failed after updating to 3.1.2

### ISSUE THREAD

**Issue by chnerypriyono** [ChuckerTeam/chucker#239]
Hi guys, currently i've tried to update from version 3.0.1 to 3.1.2, but the code cannot compiled with this error message:

Android resource linking failed

     /home/jenkins/.gradle/caches/transforms-2/files-2.1/ad918992769bab2a93527e73fcb19b3b/library-3.1.2/res/values/values.xml:92:5-104:13: AAPT: error: style attribute 'attr/colorSurface (aka com.****.****:attr/colorSurface)' not found.
         
     /home/jenkins/.gradle/caches/transforms-2/files-2.1/ad918992769bab2a93527e73fcb19b3b/library-3.1.2/res/values/values.xml:92:5-104:13: AAPT: error: style attribute 'attr/colorOnPrimary (aka com.****.****:attr/colorOnPrimary)' not found.
         
     /home/jenkins/.gradle/caches/transforms-2/files-2.1/ad918992769bab2a93527e73fcb19b3b/library-3.1.2/res/values/values.xml:92:5-104:13: AAPT: error: style attribute 'attr/colorOnSecondary (aka com.****.****:attr/colorOnSecondary)' not found.
         
     /home/jenkins/.gradle/caches/transforms-2/files-2.1/ad918992769bab2a93527e73fcb19b3b/library-3.1.2/res/values/values.xml:92:5-104:13: AAPT: error: style attribute 'attr/colorOnBackground (aka com.****.****:attr/colorOnBackground)' not found.
         
     /home/jenkins/.gradle/caches/transforms-2/files-2.1/ad918992769bab2a93527e73fcb19b3b/library-3.1.2/res/values/values.xml:92:5-104:13: AAPT: error: style attribute 'attr/colorOnSurface (aka com.****.****:attr/colorOnSurface)' not found.
         
     /home/jenkins/.gradle/caches/transforms-2/files-2.1/ad918992769bab2a93527e73fcb19b3b/library-3.1.2/res/values/values.xml:92:5-104:13: AAPT: error: style attribute 'attr/colorOnError (aka com.****.****:attr/colorOnError)' not found.
         
But if i revert it back to 3.0.1 then everything is working fine again and compiling successfully

Any idea why? Thanks before :)

**Comment by vbuberen** [comment]
Hi @chnerypriyono 
It seems that you have some issues with build cache, because Chucker has no `colorSurface` values or something like that.
For example, here is how `colorOnPrimary` defined like that:
` <item name="colorOnPrimary">@color/chucker_color_on_primary</item>`
Same thing with styles.

Can you try to build locally? 
I suppose this is Jenkins, since you have `jenkins` folder name in your error logs.

**Comment by chnerypriyono** [comment]
hi @vbuberen 
thanks a lot for your reply!
will try your suggestions and give the update here 👍

**Comment by chnerypriyono** [comment]
hi @vbuberen 
actually i've found that the issue is i haven't upgrade the version of material-component from 1.0.0 to 1.1.0, so it cannot recognize attr colorOnPrimary, colorOnSecondary, etc

after i upgrade the material-component to 1.1.0, the code compiled successfully, but another issue arises when i try to open the chucker ui screen, it crash, saying:

java.lang.NoSuchMethodError: No direct method <init>(Landroidx/lifecycle/ViewModelStoreOwner;)V in class Landroidx/lifecycle/ViewModelProvider; or its super classes (declaration of 'androidx.lifecycle.ViewModelProvider' appears in /data/app/com.***.***-VJ0TWWqIz22Xmobri8QP6w==/base.apk!classes2.dex)
        at com.chuckerteam.chucker.internal.ui.MainActivity.onCreate(MainActivity.kt:35)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Any idea why? thanks before :)

**Comment by vbuberen** [comment]
Hmm, which version of `lifecycle` (ViewModel) do you use? In 3.1.2 I updated the version used by Chucker to the latest one, which has new function for getting ViewModel.

https://developer.android.com/jetpack/androidx/releases/lifecycle#2.2.0 (look at the second item in the `Important changes section`)

**Comment by chnerypriyono** [comment]
hi @vbuberen , i've noticed that currently i'm using lifecycle 2.1.0, and after upversioning to 2.2.0 everything works fine now! Thanks a lot for the help @vbuberen , so helpful 👍

**Comment by vbuberen** [comment]
@chnerypriyono you are welcome.

Closing this, since it seems resolved.

**Comment by dodangduong** [comment]
@vbuberen Hi I'm building file .arr when i import file arr into my project and then i build this project then i got an error:
### _No direct method <init>(Landroidx/lifecycle/ViewModelStoreOwner;)V in class Landroidx/lifecycle/ViewModelProvider; or its super classes (declaration of 'androidx.lifecycle.ViewModelProvider' appears in /data/app/com.example.appfunads-V2A1iaKS3geA_oWAZA7V_g==/base.apk)_ 

i'm using lifecycle 2.2.0 
this is mycode: 
AdsModel adsModel = new ViewModelProvider((ViewModelStoreOwner) context).get(AdsModel.class);

can you help me.
Thank!
